### ISSUE TITLE
TypeError: gm.resize is not a function

### ISSUE THREAD

**Issue by adamreisnz** [fhemberger/imagemin-gm#9]
I'm getting this error after upgrading to 2.0.0:

`TypeError: gm.resize is not a function`

Didn't see anything about any breaking changes related to this function in 2.0.0.

Any thoughts?

**Comment by fhemberger** [comment]
Did you instantiate it? This was the breaking change in 2.0.0 (line 3):

```js
const imagemin = require('imagemin')
const ImageminGm = require('imagemin-gm')
const imageminGm = new ImageminGm()

const plugins = [
  imageminGm.resize({ width: 250, height: 250, gravity: 'Center' }),
  imageminGm.convert('jpg')
]

imagemin(['images/*.gif'], 'output', { use: plugins })
  .then(() => console.log('Images converted'))
  .catch(err => console.error(err))
```

It allows you to pass the gm binary path as parameter.

**Comment by adamreisnz** [comment]
Hmm, no, I wasn't aware I had to instantiate now.

The release notes just specified :

>  BREAKING CHANGE: Constructor allows gm binary path as option

So I didn't deduce from that that instantiation is now mandatory. Will give it a try and let you know, thanks! Maybe this should be clarified a bit better in the release notes.

**Comment by fhemberger** [comment]
Yes, you are right. I just had it in the README, will fix the release notes as well. Thanks!

**Comment by adamreisnz** [comment]
Awesome, thanks
